version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/onstar2mqtt-bigthundersr-vehicle1"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/onstar2mqtt-bigthundersr-vehicle2"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/onstar2mqtt-michaelwoods-vehicle1"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/onstar2mqtt-michaelwoods-vehicle2"
    schedule:
      interval: "weekly"
