# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: x - Example add-on
version: "1.2.2"
slug: example
description: Example add-on
codenotary: bigthundersr@outlook.com
url: "https://github.com/home-assistant/addons-example/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/bigthundersr/{arch}-addon-example"
