name: Submit an Issue
description: Open an issue to report a bug or request a feature.
title: '[Issue] Please replace with a clear and concise title'

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this request for your issue! Please use the discussions tab for general questions or help with the project.

  - type: textarea
    id: description
    attributes:
      label: Describe the Issue
      description: A clear and concise description of what the issue is.
      placeholder: Describe the issue
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Type of Issue
      description: Was this working before and it has since stopped working, is this a net new issue (never worked before), a bug or a feature request?
      multiple: false
      options:
        - Please select an option
        - Working before
        - Net new issue
        - Bug      
        - Feature request          
        - Enhancement          
        - Other
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: To Reproduce
      description: |
        Steps to reproduce the behavior (**Note: these are generic steps, please replace with your own steps**):

        1. Start '...'
        2. Try '...'
        3. Do '...'
        4. See error
      placeholder: Steps to reproduce the behavior
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Expected result
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Sanitized Log Output
      description: |
        If applicable, add sanitized log output (remove any sensitive information) to help explain your problem.
      placeholder: Sanitized log output

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Add screenshots

  - type: input
    id: ha_version
    attributes:
      label: Home Assistant Version
      description: e.g. 2025.1.0
      placeholder: Home Assistant Version
    validations:
      required: true

  - type: input
    id: ha_installation
    attributes:
      label: Type of Home Assistant Installation
      description: e.g. Home Assistant OS, Home Assistant Supervised, Home Assistant Container, Home Assistant Core, Home Assistant VM
      placeholder: Type of Home Assistant Installation
    validations:
      required: true

  - type: input
    id: addon_version
    attributes:
      label: Version of the Add-on
      description: e.g. 1.20.0
      placeholder: Version of the Add-on
    validations:
      required: true

  - type: input
    id: other_environment_details
    attributes:
      label: Other Relevant Environment Details
      description: Any other relevant environment details
      placeholder: Other Environment Details
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Additional context
