name: Submit an Issue
description: Open an issue to report a bug or request a feature.
title: "[Issue]: <Please replace with a clear and concise title>" 

body:
  - type: markdown
    attributes:
      value: |
        ## 📍 Please confirm which version you're using
        
        This repository supports the **Home Assistant Add-on** version of onstar2mqtt.
        
        **You're in the right place if you:**
        - Installed onstar2mqtt from the Home Assistant Add-on Store
        - Are running onstar2mqtt as a Home Assistant Supervisor add-on
        
        **If you're using the standalone Docker version** (`docker run` or `docker-compose`), please submit your issue at [BigThunderSR/onstar2mqtt](https://github.com/BigThunderSR/onstar2mqtt/issues/new) instead — that repo is specifically for the Docker container version.
        
        ---
        
        For general questions or help, please use the [Discussions](https://github.com/BigThunderSR/homeassistant-addons-onstar2mqtt/discussions) tab.

  - type: checkboxes
    id: version-confirmation
    attributes:
      label: "Version Confirmation"
      description: "Please confirm which version you're using"
      options:
        - label: "I'm using the Home Assistant Add-on version (not the standalone Docker version)"
          required: true

  - type: dropdown
    id: type
    attributes:
      label: Type of Issue
      description: What type of issue are you reporting?
      multiple: false
      options:
        - --- Please select an option ---
        - Bug (regression - was working before)
        - Bug (never worked)
        - Feature Request / Enhancement
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the Issue
      description: A clear and concise description of what the issue is.
      placeholder: Describe the issue
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: To Reproduce
      description: |
        Steps to reproduce the behavior (**Note: these are generic steps, please replace with your own steps**):

        1. Start '...'
        2. Try '...'
        3. Do '...'
        4. See error
      placeholder: Steps to reproduce the behavior
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Expected result
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Sanitized Log Output
      description: |
        If applicable, add sanitized log output to help explain your problem.
        **IMPORTANT: Remove VIN, username, password, PIN, tokens, and location data before posting.**
      placeholder: Sanitized log output

  - type: textarea
    id: getvehicledetails_output
    attributes:
      label: Output from Running "GetVehicleDetails" Command
      description: |
        For sensor and command errors/issues, please provide the output from running the `GetVehicleDetails` command (remove any sensitive information).
      placeholder: Output from running "GetVehicleDetails" command

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Add screenshots

  - type: markdown
    attributes:
      value: |
        ## Environment Information

  - type: input
    id: ha_version
    attributes:
      label: Home Assistant Version
      description: e.g. 2025.1.0
      placeholder: Home Assistant Version
    validations:
      required: true

  - type: input
    id: ha_installation
    attributes:
      label: Type of Home Assistant Installation
      description: e.g. Home Assistant OS, Home Assistant Supervised, Home Assistant Container, Home Assistant Core, Home Assistant VM
      placeholder: Type of Home Assistant Installation
    validations:
      required: true

  - type: input
    id: addon_version
    attributes:
      label: Version of the Add-on
      description: e.g. 1.20.0
      placeholder: Version of the Add-on
    validations:
      required: true

  - type: input
    id: other_environment_details
    attributes:
      label: Other Environment Details
      description: Any other relevant environment details (e.g., MQTT broker type, network setup, reverse proxy)
      placeholder: Other environment details

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Additional context
