name: Y - Do NOT Install - Testing - OnStar2MQTT Home Assistant Add-on (BigThunderSR) for Vehicle 1
version: 1.3.41
slug: y_test_onstar2mqtt_bigthundersr_vehicle1
description: Do NOT Install - Testing - Home Assistant Add On Version of BigThunderSR/onstar2mqtt for Vehicle 1
codenotary: bigthundersr@outlook.com
#startup: application
#boot: auto
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
url: "https://github.com/BigThunderSR/homeassistant-addons-onstar2mqtt"
image: "ghcr.io/bigthundersr/test-ha-addons-onstar2mqtt-btsr-test2-veh1-{arch}"
services:
  - "mqtt:need"
init: false
options:
  VEHICLE_NAME: "Vehicle 1"
  ONSTAR_DEVICEID: ""
  ONSTAR_VIN: ""
  ONSTAR_USERNAME: ""
  ONSTAR_PASSWORD: ""
  ONSTAR_PIN: ""
  ONSTAR_URL: "https://api.gm.com" #This value is hard coded in the program code and cannot be changed at this time
  ONSTAR_REFRESH: 1800000
  ONSTAR_POLL_INTERVAL: 6
  ONSTAR_POLL_TIMEOUT: 90
  MQTT_HOST: ""
  MQTT_USERNAME: ""
  MQTT_PASSWORD: ""
  MQTT_PORT: 1883
  MQTT_PREFIX: "homeassistant"
  MQTT_ONSTAR_POLLING_STATUS_TOPIC: "homeassistant/onstar2mqtt/vehicle2/polling"
schema:
  VEHICLE_NAME: str
  ONSTAR_DEVICEID: str
  ONSTAR_VIN: str
  ONSTAR_USERNAME: str
  ONSTAR_PASSWORD: password
  ONSTAR_PIN: password
  ONSTAR_URL: str
  ONSTAR_REFRESH: int
  ONSTAR_POLL_INTERVAL: int
  ONSTAR_POLL_TIMEOUT: int
  MQTT_HOST: str
  MQTT_USERNAME: str
  MQTT_PASSWORD: password
  MQTT_PORT: port
  MQTT_PREFIX: str
  MQTT_ONSTAR_POLLING_STATUS_TOPIC: str

