---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-builder:latest
  amd64: ghcr.io/home-assistant/amd64-builder:latest
  armhf: ghcr.io/home-assistant/armhf-builder:latest
  armv7: ghcr.io/home-assistant/armv7-builder:latest
  i386: ghcr.io/home-assistant/i386-builder:latest

codenotary:
  signer: bigthundersr@outlook.com