name: Builder

permissions:
  contents: read
  id-token: write
  pull-requests: write
  packages: write

env:
  MONITORED_FILES: "build.yaml config.yaml Dockerfile rootfs"
  #MONITORED_FILES: "Dockerfile rootfs"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  #workflow_run:
  #  workflows: ["Lint"]
  #  types: [completed]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  init:
    runs-on: ubuntu-latest
    name: Initialize builds
    outputs:
      changed_addons: ${{ steps.changed_addons.outputs.addons }}
      changed: ${{ steps.changed_addons.outputs.changed }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v6

      - name: Get changed files
        id: changed_files
        if: github.event_name != 'workflow_dispatch'
        #uses: jitterbit/get-changed-files@v1
        uses: HanseltimeIndustries/get-changed-files@v1.1.2

      - name: Find add-on directories
        id: addons
        uses: home-assistant/actions/helpers/find-addons@master

      - name: Get changed add-ons
        id: changed_addons
        env:
          CHANGED_FILES: ${{ steps.changed_files.outputs.all }}
        run: |
          declare -a changed_addons
          for addon in ${{ steps.addons.outputs.addons }}; do
            if [[ "$CHANGED_FILES" =~ $addon ]]; then
              for file in ${{ env.MONITORED_FILES }}; do
                  if [[ "$CHANGED_FILES" =~ $addon/$file ]]; then
                    if [[ ! "${changed_addons[@]}" =~ $addon ]]; then
                      changed_addons+=("\"${addon}\",");
                    fi
                  fi
              done
            fi
          done

          changed=$(echo ${changed_addons[@]} | rev | cut -c 2- | rev)

          if [[ -n ${changed} ]]; then
            echo "Changed add-ons: $changed";
            echo "changed=true" >> $GITHUB_OUTPUT;
            echo "addons=[$changed]" >> $GITHUB_OUTPUT;
          else
            echo "No add-on had any monitored files changed (${{ env.MONITORED_FILES }})";
          fi

  build:
    needs: init
    if: needs.init.outputs.changed == 'true'
    strategy:
      fail-fast: false
      matrix:
        addon: ${{ fromJson(needs.init.outputs.changed_addons) }}
    uses: ./.github/workflows/build-addon.yaml
    with:
      addon: ${{ matrix.addon }}
      publish: ${{ github.event_name == 'push' }}
    secrets: inherit
    #permissions:
    #  contents: read
    #  packages: write
