name: Compare Template

on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight
  workflow_dispatch:

jobs:
  compare:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout downstream project
      uses: actions/checkout@v3
      with:
        path: downstream

    - name: Checkout template repository
      uses: actions/checkout@v3
      with:
        repository: home-assistant/addons-example
        path: template

    - name: Compare builder.yaml files
      run: |
        diff -u downstream/.github/workflows/builder.yaml template/.github/workflows/builder.yaml