name: Update Submodules

on:
  #schedule:
  #  - cron: '0 0 * * *' # This will run the workflow daily at midnight
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Restrict permissions to only what is needed
      id-token: write # Required for secure authentication if needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive # Checkout submodules recursively
          token: ${{ secrets.GITHUB_TOKEN }} # Explicitly use the token securely

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions-bot@users.noreply.github.com'

      - name: Import GPG private key for signing
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --yes --pinentry-mode loopback --import
          GPG_KEY_ID=$(gpg --list-secret-keys --keyid-format LONG | grep sec | awk '{print $2}' | cut -d'/' -f2)
          echo -e "5\ny\n" | gpg --command-fd 0 --pinentry-mode loopback --expert --edit-key "$GPG_KEY_ID" trust
          gpg --batch --yes --default-key "$GPG_KEY_ID"
        shell: bash

      - name: Configure Git for GPG signing
        run: |
          GPG_KEY_ID=$(gpg --list-secret-keys --keyid-format LONG | grep sec | awk '{print $2}' | cut -d'/' -f2)
          git config --global user.signingkey "$GPG_KEY_ID"
          git config --global commit.gpgsign true
        shell: bash

      - name: Update from upstream
        run: |
          cd ./submodules/bigthundersr/onstar2mqtt
          git pull
        shell: bash

      - name: Run link script
        run: |
          cd submodules
          sh link_bigthundersr.sh
        shell: bash

      - name: Commit and push changes
        run: |
          git add .
          if ! git diff-index --quiet HEAD; then
            echo "${{ secrets.GPG_PASSPHRASE }}" | gpg --batch --yes --pinentry-mode loopback --passphrase-fd 0 --sign
            git commit -S -m "Pick up upstream updates"
            git push
          else
            echo "No changes to commit"
          fi
        shell: bash

      - name: Cleanup GPG key
        run: |
          gpg --batch --delete-secret-keys "$(gpg --list-secret-keys --keyid-format LONG | grep sec | awk '{print $2}' | cut -d'/' -f2)"
        shell: bash
